### ISSUE TITLE
Sveltekit typescript example does not work

### ISSUE THREAD

**Issue by weaseldotro** [metonym/carbon-charts-svelte-examples#1]
To reproduce, clone this repo and then:
```
cd sveltekit-typescript
npm i
npm run dev
```
When I go to http://localhost:3000/ the console shows the following error a few times:
```
10:52:28 AM [vite] Error when evaluating SSR module /src/routes/Basic.svelte:
/home/weasel/projects/carbon-charts-svelte-examples/sveltekit-typescript/node_modules/@carbon/charts/interfaces/index.js:1
export * from './a11y';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at nodeRequire (/home/weasel/projects/carbon-charts-svelte-examples/sveltekit-typescript/node_modules/vite/dist/node/chunks/dep-55830a1a.js:66473:17)
    at ssrImport (/home/weasel/projects/carbon-charts-svelte-examples/sveltekit-typescript/node_modules/vite/dist/node/chunks/dep-55830a1a.js:66415:20)
    at eval (/src/routes/Basic.svelte:9:37)
```
The browser also shows this error.
If I refresh the browser, the error goes away and the charts are showed correctly in the browser.
If I remove the `Basic` and `Events` imports and components from `index.svelte` and leave only the `DynamicImport`, there are no errors.

The `sveltekit` example (without typescript) works fine, there are no errors.

If this not related to this repo but more of a problem with the main library https://github.com/carbon-design-system/carbon-charts/tree/master/packages/svelte then I'm sorry for posting here and I can create the issue in that repo if you wish.

**Comment by benmccann** [comment]
It's the following two lines causing the issue:

https://github.com/metonym/carbon-charts-svelte-examples/blob/ae73a0d9cdde32d8aa2075a1808f154d2bc83e0f/sveltekit-typescript/src/routes/Basic.svelte#L3
https://github.com/metonym/carbon-charts-svelte-examples/blob/ae73a0d9cdde32d8aa2075a1808f154d2bc83e0f/sveltekit-typescript/src/routes/Events.svelte#L4

It's not valid to do an import from `@carbon/charts/interfaces`. You can only import from `@carbon/charts` unless `@carbon/charts` has an exports map which defines `interfaces`, which it doesn't.

**Comment by metonym** [comment]
@benmccann Nice catch!

**Comment by metonym** [comment]
I've updated the `sveltekit-typescript` examples with the [following workaround](https://github.com/metonym/carbon-charts-svelte-examples/commit/4969ba0358e0821f18f8cb3d79c7438cc732844d#diff-05ee039fa29c08bb12b5a742ae11d399218b4543149b70f63cd4df7f1469ca0a):

- import ScaleTypes as a type
- cast the scale type as as the ScaleTypes enum

```svelte
<script lang="ts">
  import { BarChartSimple } from "@carbon/charts-svelte";
  import type { BarChartOptions, ScaleTypes } from "@carbon/charts/interfaces";

  const options: BarChartOptions = {
    title: "Simple bar (discrete)",
    height: "400px",
    axes: {
      left: { mapsTo: "value" },
      bottom: { mapsTo: "group", scaleType: "labels" as ScaleTypes.LABELS },
    },
  };
</script>

<BarChartSimple
  data={[
    { group: "Qty", value: 65000 },
    { group: "More", value: 29123 },
    { group: "Sold", value: 35213 },
    { group: "Restocking", value: 51213 },
    { group: "Misc", value: 16932 },
  ]}
  {options}
/>

```

**Comment by metonym** [comment]
Commenting for posterity in case anyone stumbles upon this.

I recently tried this again and the enums/interfaces seem to work perfectly (no more need for casting).

From the [sveltekit-typescript](https://github.com/metonym/carbon-charts-svelte-examples/tree/master/sveltekit-typescript) example:

```svelte
<script lang="ts">
  import { BarChartSimple, ScaleTypes, type BarChartOptions  } from "@carbon/charts-svelte";

  const options: BarChartOptions = {
    title: "Simple bar (discrete)",
    height: "400px",
    axes: {
      left: { mapsTo: "value" },
      bottom: { mapsTo: "group", scaleType: ScaleTypes.LABELS },
    },
  };
</script>

<BarChartSimple
  data={[
    { group: "Qty", value: 65000 },
    { group: "More", value: 29123 },
    { group: "Sold", value: 35213 },
    { group: "Restocking", value: 51213 },
    { group: "Misc", value: 16932 },
  ]}
  {options}
/>

```
